image: maven:3.9.0-amazoncorretto-17

cache:
  paths:
    - .m2/repository/
    - target/

services:
  - docker:dind

stages:
  - build
  - test
  - artefact

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository -DargLine=-Dfile.encoding=UTF-8"
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_IMAGE_NAME: pex
  DOCKERFILE_PATH: .

.with-cache: &with-cache
  cache:
    key: privex-cache
    paths:
      - ~/.m2/repository

build-job:
  <<: *with-cache
  stage: build
  script: mvn $MAVEN_OPTS package -Dskip.unit.tests

unit-test-job:
  <<: *with-cache
  stage: test
  dependencies:
    - build-job
  script: mvn $MAVEN_OPTS clean test
  artifacts:
    reports:
      junit:
        - backend/*/target/surefire-reports/TEST-*.xml

it-job:
  <<: *with-cache
  stage: test
  dependencies:
    - build-job
  script: mvn $MAVEN_OPTS verify -P it
  artifacts:
    reports:
      junit:
        - backend/*/target/failsafe-reports/TEST-*.xml

docker-build:
  image: docker:latest
  stage: artefact
  script:
    - docker login -u $DOCKER_REGISTRY_LOGIN -p $DOCKER_REGISTRY_TOKEN
    - docker build -t $DOCKER_REGISTRY_LOGIN/$DOCKER_IMAGE_NAME $DOCKERFILE_PATH
    - docker push $DOCKER_REGISTRY_LOGIN/$DOCKER_IMAGE_NAME