pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: 'jenkins']],
                          userRemoteConfigs: [[url: 'https://github.com/t0lia/private-exchange.git']]])
            }
        }
        stage('Build') {
            steps {
                sh 'echo hello'
                sh 'docker --version'
            }
        }
    }
}
