pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "maven 3.8.7"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: 'jenkins']],
                          userRemoteConfigs: [[url: 'https://github.com/t0lia/private-exchange.git']]])
            }
        }

        stage('Build') {
            steps {
                sh './mvnw clean package -PbuildOnly'
            }
        }
    }
}
